const exerciseData = [
  {
    id: 1,
    name: {
      en: "Cat-Cow Stretch",
      id: "Peregangan Kucing-Sapi",
      zh: "猫牛式伸展",
      ms: "Regangan Kucing-Lembu",
      ja: "キャットカウストレッチ",
      ko: "캣카우 스트레칭",
    },
    duration: 30,
    reps: {
      en: "5-8 times",
      id: "5-8 kali",
      zh: "5-8次",
      ms: "5-8 kali",
      ja: "5-8回",
      ko: "5-8회",
    },
    icon: "solar:cat-bold-duotone",
    steps: {
      en: [
        "Get on all fours, hands under shoulders, knees under hips",
        "Inhale: arch your back down, lift your head (Cow)",
        "Exhale: round your back up, tuck your chin (Cat)",
        "Move slowly with your breathing rhythm",
      ],
      id: [
        "Posisi merangkak, tangan di bawah bahu, lutut di bawah pinggul",
        "Tarik napas: lengkungkan punggung ke bawah, angkat kepala (Cow)",
        "Buang napas: bulatkan punggung ke atas, tundukkan kepala (Cat)",
        "Lakukan perlahan dengan irama napas",
      ],
      zh: [
        "四肢着地，双手在肩膀下方，膝盖在臀部下方",
        "吸气：背部向下弯曲，抬起头部（牛式）",
        "呼气：背部向上拱起，低下头部（猫式）",
        "跟随呼吸节奏缓慢进行",
      ],
      ms: [
        "Posisi merangkak, tangan di bawah bahu, lutut di bawah pinggul",
        "Tarik nafas: lengkungkan belakang ke bawah, angkat kepala (Lembu)",
        "Hembus nafas: bulatkan belakang ke atas, tundukkan kepala (Kucing)",
        "Lakukan perlahan mengikut irama nafas",
      ],
      ja: [
        "四つん這いになり、手は肩の下、膝は腰の下に",
        "息を吸う：背中を下に反らし、頭を上げる（カウ）",
        "息を吐く：背中を上に丸め、頭を下げる（キャット）",
        "呼吸のリズムに合わせてゆっくり行う",
      ],
      ko: [
        "네 발로 엎드려 손은 어깨 아래, 무릎은 엉덩이 아래에 놓기",
        "들숨: 등을 아래로 휘고 머리를 들기 (카우)",
        "날숨: 등을 위로 둥글게 말고 턱을 당기기 (캣)",
        "호흡 리듬에 맞춰 천천히 하기",
      ],
    },
    targetMuscle: "Erector spinae, multifidus",
    benefit: {
      en: "Improves spinal flexibility and reduces stiffness",
      id: "Meningkatkan fleksibilitas tulang belakang dan mengurangi kekakuan",
      zh: "提高脊柱灵活性，减少僵硬",
      ms: "Meningkatkan fleksibiliti tulang belakang dan mengurangkan kekakuan",
      ja: "脊椎の柔軟性を向上させ、硬直を軽減する",
      ko: "척추 유연성을 향상시키고 뻣뻣함을 줄여줍니다",
    },
  },
  {
    id: 2,
    name: {
      en: "Knee-to-Chest Stretch",
      id: "Lutut ke Dada",
      zh: "膝盖抱胸",
      ms: "Regangan Lutut ke Dada",
      ja: "膝を胸に引き寄せるストレッチ",
      ko: "무릎 가슴 당기기",
    },
    duration: 30,
    reps: {
      en: "Hold 15-30 sec per side",
      id: "Tahan 15-30 detik per sisi",
      zh: "每侧保持15-30秒",
      ms: "Tahan 15-30 saat setiap sisi",
      ja: "片側15-30秒キープ",
      ko: "한쪽당 15-30초 유지",
    },
    icon: "solar:body-bold-duotone",
    steps: {
      en: [
        "Lie on your back on the floor",
        "Bend one knee, gently pull it toward your chest",
        "Hold 15-30 seconds, feel the stretch in your lower back",
        "Switch legs, then try both knees together",
      ],
      id: [
        "Berbaring telentang di lantai",
        "Tekuk satu lutut, tarik perlahan ke arah dada",
        "Tahan 15-30 detik, rasakan peregangan di punggung bawah",
        "Ganti kaki, lalu coba kedua lutut bersamaan",
      ],
      zh: [
        "仰卧在地板上",
        "弯曲一条腿，轻轻拉向胸部",
        "保持15-30秒，感受下背部的拉伸",
        "换腿，然后尝试双膝一起",
      ],
      ms: [
        "Baring telentang di atas lantai",
        "Tekuk satu lutut, tarik perlahan ke arah dada",
        "Tahan 15-30 saat, rasakan regangan di belakang bawah",
        "Tukar kaki, kemudian cuba kedua-dua lutut bersama",
      ],
      ja: [
        "床に仰向けに寝る",
        "片膝を曲げ、ゆっくり胸に引き寄せる",
        "15-30秒キープし、腰の伸びを感じる",
        "脚を替え、両膝を同時に試す",
      ],
      ko: [
        "바닥에 등을 대고 눕기",
        "한쪽 무릎을 구부려 가슴 쪽으로 당기기",
        "15-30초 유지, 허리의 스트레칭 느끼기",
        "다리를 바꾸고, 양쪽 무릎을 함께 해보기",
      ],
    },
    targetMuscle: "Lower back, glutes",
    benefit: {
      en: "Releases pressure on the lower spinal nerves",
      id: "Melepaskan tekanan pada saraf tulang belakang bagian bawah",
      zh: "释放下脊椎神经的压力",
      ms: "Melepaskan tekanan pada saraf tulang belakang bahagian bawah",
      ja: "下部脊椎神経の圧力を解放する",
      ko: "하부 척추 신경의 압력을 풀어줍니다",
    },
  },
  {
    id: 3,
    name: {
      en: "Seated Spinal Twist",
      id: "Rotasi Tulang Belakang Duduk",
      zh: "坐姿脊柱扭转",
      ms: "Putaran Tulang Belakang Duduk",
      ja: "座位脊椎ツイスト",
      ko: "앉아서 척추 비틀기",
    },
    duration: 30,
    reps: {
      en: "Hold 15-20 sec per side",
      id: "Tahan 15-20 detik per sisi",
      zh: "每侧保持15-20秒",
      ms: "Tahan 15-20 saat setiap sisi",
      ja: "片側15-20秒キープ",
      ko: "한쪽당 15-20초 유지",
    },
    icon: "solar:refresh-circle-bold-duotone",
    steps: {
      en: [
        "Sit in a chair, feet flat on the floor",
        "Place your right hand on your left knee",
        "Slowly twist your body to the left, look behind",
        "Hold, feel the stretch in your back",
        "Return to center, repeat on the other side",
      ],
      id: [
        "Duduk di kursi, kaki rata di lantai",
        "Letakkan tangan kanan di lutut kiri",
        "Putar badan perlahan ke kiri, lihat ke belakang",
        "Tahan, rasakan peregangan di punggung",
        "Kembali ke tengah, ulangi sisi lainnya",
      ],
      zh: [
        "坐在椅子上，双脚平放在地板上",
        "将右手放在左膝上",
        "慢慢将身体向左扭转，看向后方",
        "保持，感受背部的拉伸",
        "回到中间，换另一侧重复",
      ],
      ms: [
        "Duduk di kerusi, kaki rata di atas lantai",
        "Letakkan tangan kanan di lutut kiri",
        "Pusingkan badan perlahan ke kiri, pandang ke belakang",
        "Tahan, rasakan regangan di belakang",
        "Kembali ke tengah, ulang sisi yang lain",
      ],
      ja: [
        "椅子に座り、足を床に平らに置く",
        "右手を左膝に置く",
        "ゆっくり体を左にひねり、後ろを見る",
        "キープし、背中の伸びを感じる",
        "中央に戻り、反対側を繰り返す",
      ],
      ko: [
        "의자에 앉아 발을 바닥에 평평하게 놓기",
        "오른손을 왼쪽 무릎에 놓기",
        "천천히 몸을 왼쪽으로 비틀고 뒤를 보기",
        "유지하며 등의 스트레칭 느끼기",
        "중앙으로 돌아와 반대쪽 반복",
      ],
    },
    targetMuscle: "Obliques, erector spinae, multifidus",
    benefit: {
      en: "Can be done at your desk, improves rotational mobility",
      id: "Bisa dilakukan di kursi kerja, meningkatkan mobilitas rotasi",
      zh: "可以在办公桌前完成，提高旋转灵活性",
      ms: "Boleh dilakukan di kerusi kerja, meningkatkan mobiliti putaran",
      ja: "デスクでできる、回旋の可動性を向上",
      ko: "책상에서 할 수 있으며 회전 운동성을 향상시킵니다",
    },
  },
  {
    id: 4,
    name: {
      en: "Standing Back Extension",
      id: "Ekstensi Punggung Berdiri",
      zh: "站立背部伸展",
      ms: "Ekstensi Belakang Berdiri",
      ja: "立位バックエクステンション",
      ko: "서서 등 펴기",
    },
    duration: 20,
    reps: {
      en: "5-8 times",
      id: "5-8 kali",
      zh: "5-8次",
      ms: "5-8 kali",
      ja: "5-8回",
      ko: "5-8회",
    },
    icon: "solar:user-bold-duotone",
    steps: {
      en: [
        "Stand straight, place both hands on your lower back",
        "Slowly arch your back backward",
        "Hold 2-3 seconds at the end position",
        "Return to standing position",
      ],
      id: [
        "Berdiri tegak, letakkan kedua tangan di punggung bawah",
        "Perlahan lengkungkan punggung ke belakang",
        "Tahan 2-3 detik di posisi akhir",
        "Kembali ke posisi tegak",
      ],
      zh: [
        "站直，双手放在下背部",
        "慢慢向后弯曲背部",
        "在最终位置保持2-3秒",
        "回到站立姿势",
      ],
      ms: [
        "Berdiri tegak, letakkan kedua-dua tangan di belakang bawah",
        "Perlahan lengkungkan belakang ke belakang",
        "Tahan 2-3 saat di posisi akhir",
        "Kembali ke posisi tegak",
      ],
      ja: [
        "真っ直ぐ立ち、両手を腰に当てる",
        "ゆっくり背中を後ろに反らす",
        "最終位置で2-3秒キープ",
        "立位に戻る",
      ],
      ko: [
        "똑바로 서서 양손을 허리에 대기",
        "천천히 등을 뒤로 젖히기",
        "끝 위치에서 2-3초 유지",
        "서 있는 자세로 돌아오기",
      ],
    },
    targetMuscle: "Erector spinae, lumbar extensors",
    benefit: {
      en: "Counterbalances hunched sitting posture, easy to do anywhere",
      id: "Counterbalance posisi duduk membungkuk, mudah dilakukan di mana saja",
      zh: "平衡弯腰久坐的姿势，随时随地都能做",
      ms: "Mengimbangi postur duduk membongkok, mudah dilakukan di mana-mana",
      ja: "猫背の座位姿勢を補正、どこでもできる",
      ko: "구부정한 앉는 자세를 보완하며 어디서든 할 수 있습니다",
    },
  },
  {
    id: 5,
    name: {
      en: "Child's Pose",
      id: "Pose Anak",
      zh: "婴儿式",
      ms: "Pose Kanak-kanak",
      ja: "チャイルドポーズ",
      ko: "차일드 포즈",
    },
    duration: 45,
    reps: {
      en: "Hold 30-45 sec",
      id: "Tahan 30-45 detik",
      zh: "保持30-45秒",
      ms: "Tahan 30-45 saat",
      ja: "30-45秒キープ",
      ko: "30-45초 유지",
    },
    icon: "solar:meditation-round-bold-duotone",
    steps: {
      en: [
        "Kneel down, sit on your heels",
        "Stretch your arms forward, forehead to the floor",
        "Breathe deeply, feel your back lengthening",
        "Relax and hold the position",
      ],
      id: [
        "Berlutut, duduk di atas tumit",
        "Rentangkan tangan ke depan, dahi ke lantai",
        "Tarik napas dalam, rasakan punggung memanjang",
        "Rileks dan tahan posisi",
      ],
      zh: [
        "跪下，坐在脚跟上",
        "双臂向前伸展，额头贴地",
        "深呼吸，感受背部的延伸",
        "放松并保持姿势",
      ],
      ms: [
        "Berlutut, duduk di atas tumit",
        "Rentangkan tangan ke hadapan, dahi ke lantai",
        "Tarik nafas dalam, rasakan belakang memanjang",
        "Relaks dan tahan posisi",
      ],
      ja: [
        "膝をつき、かかとの上に座る",
        "腕を前に伸ばし、額を床につける",
        "深く呼吸し、背中が伸びるのを感じる",
        "リラックスして姿勢をキープ",
      ],
      ko: [
        "무릎을 꿇고 발뒤꿈치 위에 앉기",
        "팔을 앞으로 뻗고 이마를 바닥에 대기",
        "깊게 호흡하며 등이 늘어나는 것을 느끼기",
        "편안하게 자세 유지하기",
      ],
    },
    targetMuscle: "Lower back, lats, hips",
    benefit: {
      en: "A very relaxing passive stretch for the entire back",
      id: "Peregangan pasif yang sangat relaksasi untuk seluruh punggung",
      zh: "非常放松的被动拉伸，适用于整个背部",
      ms: "Regangan pasif yang sangat menenangkan untuk seluruh belakang",
      ja: "背中全体の非常にリラックスできる受動的ストレッチ",
      ko: "등 전체를 위한 매우 편안한 수동적 스트레칭",
    },
  },
  {
    id: 6,
    name: {
      en: "Piriformis Stretch",
      id: "Peregangan Piriformis",
      zh: "梨状肌拉伸",
      ms: "Regangan Piriformis",
      ja: "梨状筋ストレッチ",
      ko: "이상근 스트레칭",
    },
    duration: 30,
    reps: {
      en: "Hold 20-30 sec per side",
      id: "Tahan 20-30 detik per sisi",
      zh: "每侧保持20-30秒",
      ms: "Tahan 20-30 saat setiap sisi",
      ja: "片側20-30秒キープ",
      ko: "한쪽당 20-30초 유지",
    },
    icon: "solar:armchair-bold-duotone",
    steps: {
      en: [
        "Sit in a chair, lift your right leg, place ankle on left knee (figure-4)",
        "Keep your back straight, slowly lean forward",
        "Feel the stretch in your right buttock and hip",
        "Hold, then switch sides",
      ],
      id: [
        "Duduk di kursi, angkat kaki kanan, taruh ankle di lutut kiri (figure-4)",
        "Tegakkan punggung, perlahan condongkan badan ke depan",
        "Rasakan peregangan di bokong dan pinggul kanan",
        "Tahan, lalu ganti sisi",
      ],
      zh: [
        "坐在椅子上，抬起右腿，将脚踝放在左膝上（4字型）",
        "保持背部挺直，慢慢向前倾",
        "感受右侧臀部和髋部的拉伸",
        "保持，然后换边",
      ],
      ms: [
        "Duduk di kerusi, angkat kaki kanan, letak buku lali di lutut kiri (figure-4)",
        "Tegakkan belakang, perlahan condongkan badan ke hadapan",
        "Rasakan regangan di punggung dan pinggul kanan",
        "Tahan, kemudian tukar sisi",
      ],
      ja: [
        "椅子に座り、右脚を上げ、足首を左膝に置く（4の字）",
        "背筋を伸ばし、ゆっくり前に傾く",
        "右のお尻と股関節の伸びを感じる",
        "キープし、反対側に替える",
      ],
      ko: [
        "의자에 앉아 오른쪽 다리를 들어 발목을 왼쪽 무릎에 놓기 (4자)",
        "등을 곧게 펴고 천천히 앞으로 기울기",
        "오른쪽 엉덩이와 골반의 스트레칭 느끼기",
        "유지한 후 반대쪽 반복",
      ],
    },
    targetMuscle: "Piriformis, deep hip rotators, glutes",
    benefit: {
      en: "Often related to sciatica, can be done at your desk",
      id: "Sering terkait sciatica, bisa dilakukan di kursi kerja",
      zh: "常与坐骨神经痛相关，可在办公桌前完成",
      ms: "Sering berkaitan sciatica, boleh dilakukan di kerusi kerja",
      ja: "坐骨神経痛に関連、デスクでできる",
      ko: "좌골신경통과 관련이 있으며 책상에서 할 수 있습니다",
    },
  },
  {
    id: 7,
    name: {
      en: "Pelvic Tilt",
      id: "Tilt Pelvis",
      zh: "骨盆倾斜",
      ms: "Senget Pelvis",
      ja: "ペルビックティルト",
      ko: "골반 기울이기",
    },
    duration: 25,
    reps: {
      en: "10-15 times",
      id: "10-15 kali",
      zh: "10-15次",
      ms: "10-15 kali",
      ja: "10-15回",
      ko: "10-15회",
    },
    icon: "solar:round-transfer-vertical-bold-duotone",
    steps: {
      en: [
        "Lie on your back, bend knees, feet flat on the floor",
        "Tighten your abdominal muscles, flatten your back to the floor",
        "Hold 5 seconds, then relax",
        "Repeat with a steady rhythm",
      ],
      id: [
        "Berbaring telentang, tekuk lutut, kaki rata di lantai",
        "Kencangkan otot perut, ratakan punggung ke lantai",
        "Tahan 5 detik, lalu rileks",
        "Ulangi dengan ritme yang stabil",
      ],
      zh: [
        "仰卧，弯曲膝盖，双脚平放在地板上",
        "收紧腹部肌肉，将背部压平贴地",
        "保持5秒，然后放松",
        "以稳定的节奏重复",
      ],
      ms: [
        "Baring telentang, tekuk lutut, kaki rata di atas lantai",
        "Ketatkan otot perut, ratakan belakang ke lantai",
        "Tahan 5 saat, kemudian relaks",
        "Ulang dengan irama yang stabil",
      ],
      ja: [
        "仰向けに寝て膝を曲げ、足を床に平らに置く",
        "腹筋を締め、背中を床に押し付ける",
        "5秒キープし、リラックス",
        "安定したリズムで繰り返す",
      ],
      ko: [
        "등을 대고 누워 무릎을 구부리고 발을 바닥에 평평하게 놓기",
        "복부 근육을 조이고 등을 바닥에 붙이기",
        "5초 유지 후 이완",
        "일정한 리듬으로 반복",
      ],
    },
    targetMuscle: "Transverse abdominis, multifidus",
    benefit: {
      en: "Strengthens core stabilizers, fundamental for LBP rehabilitation",
      id: "Memperkuat core stabilizer, dasar rehabilitasi LBP",
      zh: "加强核心稳定肌，是腰痛康复的基础",
      ms: "Mengukuhkan penstabil teras, asas pemulihan LBP",
      ja: "コアスタビライザーを強化、腰痛リハビリの基礎",
      ko: "코어 안정근을 강화하며 요통 재활의 기본입니다",
    },
  },
  {
    id: 8,
    name: {
      en: "Hip Flexor Stretch",
      id: "Peregangan Fleksor Pinggul",
      zh: "髋屈肌拉伸",
      ms: "Regangan Fleksor Pinggul",
      ja: "股関節屈筋ストレッチ",
      ko: "고관절 굴곡근 스트레칭",
    },
    duration: 30,
    reps: {
      en: "Hold 20-30 sec per side",
      id: "Tahan 20-30 detik per sisi",
      zh: "每侧保持20-30秒",
      ms: "Tahan 20-30 saat setiap sisi",
      ja: "片側20-30秒キープ",
      ko: "한쪽당 20-30초 유지",
    },
    icon: "solar:running-round-bold-duotone",
    steps: {
      en: [
        "Half-kneeling lunge position",
        "Front leg bent 90°, back knee on the floor",
        "Slowly push your hips forward",
        "Feel the stretch in the front of your back thigh",
        "Keep your back straight",
      ],
      id: [
        "Posisi berlutut satu kaki (half-kneeling lunge)",
        "Kaki depan ditekuk 90°, lutut belakang di lantai",
        "Dorong pinggul ke depan perlahan",
        "Rasakan peregangan di depan paha kaki belakang",
        "Jaga punggung tetap tegak",
      ],
      zh: [
        "半跪弓步姿势",
        "前腿弯曲90°，后膝着地",
        "慢慢将臀部向前推",
        "感受后腿大腿前侧的拉伸",
        "保持背部挺直",
      ],
      ms: [
        "Posisi berlutut separuh (half-kneeling lunge)",
        "Kaki depan ditekuk 90°, lutut belakang di atas lantai",
        "Tolak pinggul ke hadapan perlahan",
        "Rasakan regangan di hadapan paha kaki belakang",
        "Jaga belakang tetap tegak",
      ],
      ja: [
        "ハーフニーリングランジの姿勢",
        "前脚を90°に曲げ、後ろの膝を床につける",
        "ゆっくり腰を前に押し出す",
        "後ろ脚の太もも前面の伸びを感じる",
        "背筋を真っ直ぐに保つ",
      ],
      ko: [
        "반무릎 런지 자세",
        "앞다리 90° 굽히고, 뒷무릎은 바닥에",
        "천천히 엉덩이를 앞으로 밀기",
        "뒷다리 허벅지 앞쪽의 스트레칭 느끼기",
        "등을 곧게 유지하기",
      ],
    },
    targetMuscle: "Iliopsoas, rectus femoris",
    benefit: {
      en: "Prolonged sitting shortens hip flexors, causing anterior pelvic tilt and LBP",
      id: "Duduk lama membuat hip flexor pendek, ini menyebabkan anterior pelvic tilt dan LBP",
      zh: "久坐会缩短髋屈肌，导致骨盆前倾和腰痛",
      ms: "Duduk lama memendekkan fleksor pinggul, menyebabkan senget pelvis anterior dan LBP",
      ja: "長時間の座位は股関節屈筋を短縮させ、骨盤前傾と腰痛を引き起こす",
      ko: "오래 앉으면 고관절 굴곡근이 짧아져 골반 전방 경사와 요통을 유발합니다",
    },
  },
];

export function getExercises(lang = "en") {
  return exerciseData.map((ex) => ({
    id: ex.id,
    name: ex.name[lang] || ex.name.en,
    duration: ex.duration,
    reps: ex.reps[lang] || ex.reps.en,
    icon: ex.icon,
    steps: ex.steps[lang] || ex.steps.en,
    targetMuscle: ex.targetMuscle,
    benefit: ex.benefit[lang] || ex.benefit.en,
  }));
}

// Quick desk exercises (can be done at desk without floor)
export function getQuickDeskExercises(lang = "en") {
  return getExercises(lang).filter((e) => [3, 4, 6].includes(e.id));
}

// Get random exercises for a session
export function getSessionExercises(lang = "en", count = 3) {
  const shuffled = [...getExercises(lang)].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// Get a random quick desk exercise
export function getQuickExercise(lang = "en") {
  const quick = getQuickDeskExercises(lang);
  return quick[Math.floor(Math.random() * quick.length)];
}
